### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by ataylorme** [comment]
@zgordon per our conversation today I refactored a lot out into separate files (except attributes ;-) What do you think?

**Comment by zgordon** [comment]
Dig it.  I'm seeing both a editor.block.js and a block.js should they both be in src/js?

**Comment by ataylorme** [comment]
I have `src/js/block.editor.js` that compiles to `assets/js/block.editor.min.js` but currently, it's empty. Perhaps I should remove it.

**Comment by zgordon** [comment]
Yeah, that is just a little confusing because block.js is also loading in the editor.

**Comment by ataylorme** [comment]
Ah, I have `block.editor.js` as the editor only JS. I can see where there is confusion. I should probably rename the main file `index.js` or similar. Is there a better convention?

**Comment by zgordon** [comment]
I think having the main registerBlockType in the index.js is good.

Then if you need to pull out just the edit code to go in a block.js that is what core does. But I like not having any files named block and using specific component names and stuff instead

**Pull request merged**
